title = "config"

[web-api]
host = "localhost"
port = "8000"

[proxy-server]
host = "localhost"
port = "8080"

[database]
dbname = "docker"
username = "docker"
password = "docker"
host = "localhost"
port = "5432"